/* Cloud-only fault injection against shipped persistence and updater code.
   No hotel data, Electron process or protel installation is accessed. */
"use strict";
const fs=require('fs'),path=require('path'),os=require('os'),vm=require('vm'),assert=require('assert'),crypto=require('crypto');
const src=fs.readFileSync(path.join(__dirname,'../app/index.html'),'utf8');
function between(a,b){const start=src.indexOf(a),end=src.indexOf(b,start+a.length);assert(start>=0&&end>start,'extraction anchors');return src.slice(start,end);}
function storage(initial={}){const data={...initial};return {data,failKey:null,get length(){return Object.keys(data).length;},key:i=>Object.keys(data)[i],getItem:k=>data[k]??null,setItem(k,v){if(this.failKey===k)throw Error('QuotaExceededError');data[k]=String(v);},removeItem:k=>delete data[k]};}
function ctx(initial={}){
 const localStorage=storage(initial),toasts=[];let exported=null;
 const c={localStorage,console,Date,JSON,Object,Array,Set,MODEL:null,ROOMS:{},ROOMS_KEY:'reccheck_rooms',ROOMS_DISK_READY:false,ROOMS_DISK_PENDING:null,STATE:{date:'18/9/2026',receipts:{},extras:[]},stateKey:'reccheck_18/9/2026',NAMES_STALE:false,
  toast:(...x)=>toasts.push(x),t:k=>k,pad2:n=>String(n).padStart(2,'0'),setTimeout(){},loadWatch(){},loadAlerts(){},paintAlertsBtn(){},syncRooms(){},refresh(){},
  Blob:class{constructor(parts){exported=JSON.parse(parts.join(''));}},URL:{createObjectURL:()=>'',revokeObjectURL(){}},document:{createElement:()=>({click(){},remove(){}}),body:{append(){}}},
  FileReader:class{readAsText(text){this.result=text;this.onload();}},window:{__rcStorageFault:(...x)=>toasts.push(x)},uiFault:(...x)=>toasts.push(x)};
 vm.createContext(c);
 const recovery=src.includes('function importJournalKey(){')?between('function importJournalKey(){','if(!recoverImport())'):'';
 vm.runInContext(recovery+between('function blankState(date){','/* ---------- helpers ---------- */')+between('function exportData(){','/* ---------- refresh ---------- */')+between('function loadRooms(){','/* THE PROTEL NAMES,'),c);
 return {c,localStorage,toasts,get exported(){return exported;}};
}
const cases=[];const test=(name,fn)=>cases.push([name,fn]);
test('normal receipt state survives a reload',()=>{const x=ctx();x.c.STATE.receipts.a={status:'checked'};x.c.saveState();assert.equal(x.c.loadState('18/9/2026').receipts.a.status,'checked');});
test('quota failure on receipt save is observable instead of silent success',()=>{const x=ctx();x.localStorage.failKey=x.c.stateKey;let signalled=false;try{signalled=x.c.saveState()===false;}catch(e){signalled=true;}assert(signalled||x.toasts.length,'saveState swallowed the storage exception; a restart loses the displayed work');});
test('backup export contains Tax Check memory and decisions',()=>{const x=ctx({'reccheck_rooms':'{}','ta_check_memory_v2':'{"101":{"18/9/2026":{"auto":1}}}','ta_check_verify_v1':'{"20260918":{"101":true}}','ta_check_ack_v1':'{"101":1}'});x.c.exportData();for(const k of ['ta_check_memory_v2','ta_check_verify_v1','ta_check_ack_v1'])assert(k in x.exported.data,k+' was omitted');});
test('backup import restores Tax Check keys',()=>{const x=ctx();x.c.importData(JSON.stringify({app:'reccheck',data:{reccheck_rooms:'{}',ta_check_memory_v2:'{"101":{}}'}}));assert.equal(x.localStorage.getItem('ta_check_memory_v2'),'{"101":{}}');});
test('export/import preserves non-JSON string preferences it exports',()=>{const x=ctx({reccheck_lang:'gr'});x.c.exportData();const y=ctx();y.c.importData(JSON.stringify(x.exported));assert.equal(y.localStorage.getItem('reccheck_lang'),'gr');});
test('failed multi-key import leaves existing database consistent',()=>{const initial={reccheck_rooms:'{"101":{"guest":"CURRENT"}}',reccheck_watchlist:'[{"room":"101","name":"CURRENT"}]'};const x=ctx(initial);x.localStorage.failKey='reccheck_watchlist';x.c.importData(JSON.stringify({app:'reccheck',data:{reccheck_rooms:'{"101":{"guest":"OLD"}}',reccheck_watchlist:'[]'}}));assert.deepEqual(x.localStorage.data,initial,'rooms were replaced before failure; watchlist retained another generation');});
test('schema-invalid receipt state cannot replace a usable loaded state',()=>{const x=ctx({'reccheck_18/9/2026':'{"date":"18/9/2026","receipts":null,"extras":"broken"}'});const state=x.c.loadState('18/9/2026');assert(state.receipts&&typeof state.receipts==='object'&&Array.isArray(state.extras),'JSON syntax alone does not validate the stored state');});
test('failed room mirror is observable when local storage also fails',()=>{const x=ctx();x.localStorage.failKey='reccheck_rooms';x.c.window.reccheckRooms={write:()=>false};x.c.ROOMS={'101':{guest:'NEW'}};let signalled=false;try{signalled=x.c.saveRooms()===false;}catch(e){signalled=true;}assert(signalled||x.toasts.length,'both persistence paths failed with no error signal');});
test('disk room recovery precedes writes that can destroy the only backup',async()=>{const x=ctx();let disk={'101':{guest:'SAVED',nick:'Keep me'},'102':{guest:'OMITTED'}};x.c.window.reccheckRooms={read:async()=>JSON.parse(JSON.stringify(disk)),write:v=>{disk=JSON.parse(JSON.stringify(v));return true;}};
 // The boot IIFE awaits directory/overlay IPC before starting mergeRoomsFromDisk;
 // the independent tax boot can deliver a capture during that interval.
 x.c.ROOMS={'101':{guest:'SAVED',liveKey:20260918}};x.c.saveRooms();await x.c.mergeRoomsFromDisk();assert.equal(x.c.ROOMS['101'].nick,'Keep me');assert(x.c.ROOMS['102']);});
test('disk merge keeps an existing working room authoritative',async()=>{const x=ctx();x.c.ROOMS={'101':{guest:'NEW'}};x.c.window.reccheckRooms={read:async()=>({'101':{guest:'OLD'},'102':{guest:'OTHER'}})};await x.c.mergeRoomsFromDisk();assert.equal(x.c.ROOMS['101'].guest,'NEW');assert.equal(x.c.ROOMS['102'].guest,'OTHER');});
const {FileHub}=require('../app/files.js');
test('interrupted config save preserves previous folder/profile configuration',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'audit-config-')),f=path.join(dir,'config.json');const before=JSON.stringify({reportsDirs:{dept:'/reports'},profiles:[{id:'saved'}]});fs.writeFileSync(f,before);const real=fs.writeFileSync;try{fs.writeFileSync=function(p,...args){if(String(p)===f||String(p)===f+'.tmp'){real(p,'');throw Error('simulated full disk after truncation');}return real(p,...args);};new FileHub({configPath:f}).writeConfig({reportsDirs:{dept:'/changed'}});}finally{fs.writeFileSync=real;}assert.equal(fs.readFileSync(f,'utf8'),before);});
const {Updater}=require('../app/updater.js');
function updater(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'audit-update-'));return new Updater({userDataDir:dir,packagedDir:dir,pkgVersion:'1.0.0',updateUrl:'https://fixture.invalid/manifest',fallbackReleaseUrl:'https://fixture.invalid/release'});}
test('cached HTML is revalidated before reporting ready',async()=>{const u=updater(),p=u.paths(),valid='<!DOCTYPE html>'+('x'.repeat(11000)),sha=crypto.createHash('sha256').update(valid).digest('hex');fs.writeFileSync(p.pendMeta,JSON.stringify({version:'2.0.0',sha256:sha}));fs.writeFileSync(p.pendHtml,'truncated');const fetch=global.fetch;global.fetch=async()=>({ok:true,json:async()=>({version:'2.0.0',type:'html',html:'https://fixture.invalid/page',sha256:sha}),arrayBuffer:async()=>Buffer.from('truncated')});try{assert.equal(await u.check(),null,'corrupt cached payload was accepted as ready');}finally{global.fetch=fetch;}});
test('interrupted promotion preserves the previously working page',()=>{const u=updater(),p=u.paths(),old='<!DOCTYPE html>'+('old'.repeat(4000)),fresh='<!DOCTYPE html>'+('new'.repeat(4000)),sha=x=>crypto.createHash('sha256').update(x).digest('hex');fs.writeFileSync(p.curHtml,old);fs.writeFileSync(p.curMeta,JSON.stringify({version:'1.5.0',sha256:sha(old)}));fs.writeFileSync(p.pendHtml,fresh);fs.writeFileSync(p.pendMeta,JSON.stringify({version:'2.0.0',sha256:sha(fresh)}));u.pending={version:'2.0.0'};const real=fs.copyFileSync;let injected=false;try{fs.copyFileSync=(from,to)=>{injected=true;fs.writeFileSync(to,'PARTIAL');throw Error('simulated interrupted copy');};try{u.promote();}catch(e){}}finally{fs.copyFileSync=real;}assert(injected,'fault injection reached the copy');assert.equal(fs.readFileSync(p.curHtml,'utf8'),old);});
(async()=>{let failed=0;for(const [name,fn] of cases){try{await fn();console.log('PASS '+name);}catch(e){failed++;console.log('FAIL '+name+'\n  '+e.message);}}console.log(JSON.stringify({suite:'storage',total:cases.length,passed:cases.length-failed,failed}));process.exitCode=failed?1:0;})();
